spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olx_advertise
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@12345
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
