spring:
  datasource:
    url: jdbc:h2:mem:/mydatabaseAbcd
    username: sa
    password: 12345
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stockDb
#  datasource:
#    url: jdbc:mysql://localhost:3306/lab_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Root@12345
#  jpa:
#    hibernate.ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
